importScripts("https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js");

// Versão 12.6 — prioridade estável e tarefas restauradas.
// Patch autônomo: não depende de arquivos externos para restaurar ordem, busca, agenda e prioridade.
self.addEventListener('install', event => self.skipWaiting());
self.addEventListener('activate', event => event.waitUntil(self.clients.claim()));

const PLANNER_PATCH_CSS = `
/* Ajuste 12.6: prioridade em botão estável e tarefas acima das rotinas */
html,body{width:100%;max-width:100%;overflow-x:hidden!important;position:relative;touch-action:pan-y}
body{overscroll-behavior-x:none}
main{width:100%;max-width:780px;margin:0 auto;padding-top:28px!important;padding-bottom:24px!important;padding-left:calc(22px + env(safe-area-inset-left))!important;padding-right:calc(18px + env(safe-area-inset-right))!important;overflow:hidden}
.topbar{max-width:100%;align-items:flex-start!important;margin:8px 0 12px!important;min-height:52px!important}.hello h1{font-size:25px!important;line-height:1.04!important;letter-spacing:-.55px!important;margin:0!important;white-space:nowrap!important}.hello p{font-size:13px!important;line-height:1.25!important;margin-top:5px!important}.topActions{padding-top:2px!important;flex:none!important}.roundBtn{width:38px!important;height:38px!important}.hero{margin-top:4px!important}.heroTitle{line-height:1.2!important}
.topbar,.hero,.todayPanel,.grid,.sectionHead,.filter,.item,.toolsBox,.historyBox,.routineBox,.searchPanel{max-width:100%}.grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}.stat{min-width:0!important}.stat span{display:block;line-height:1.05!important}
#taskList .item{position:relative!important;padding-right:58px!important}.itemActions{display:flex!important;gap:8px!important;flex-wrap:wrap!important}.priorityAction{background:#fff3c4!important;color:#8a5b00!important;border:1px solid #f3d990!important}.priorityAction.on{background:#ffe08a!important;color:#7a4d00!important}.priorityNativeBtn,.priorityBtn{display:none!important}.priorityTag,.priorityNativeTag{display:inline-flex!important;align-items:center!important;gap:4px!important;background:#fff3c4!important;color:#8a5b00!important;border-radius:999px!important;padding:7px 10px!important;font-size:13px!important;font-weight:900!important;margin-right:5px!important;margin-top:5px!important}.priorityItem{border-color:#f3d990!important;box-shadow:0 12px 26px rgba(154,106,0,.10)!important}.priorityItem .itemText{color:var(--wine)!important}
.searchPanel{display:none;background:rgba(255,253,251,.96);border:1px solid var(--line);border-radius:22px;padding:14px;margin:12px 0 14px;box-shadow:var(--shadow2)}.searchPanel.open{display:block}.searchHeader{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.searchHeader b{font-size:18px;color:var(--wine)}.searchClose{border:0;background:var(--rose);color:var(--wine);border-radius:999px;width:34px;height:34px;font-size:18px;font-weight:900}.searchInputWrap{display:flex;align-items:center;gap:8px;background:white;border:1px solid var(--line);border-radius:16px;padding:10px 12px}.searchInputWrap span{color:var(--muted)}#realSearchInput{border:0!important;outline:0!important;width:100%!important;font-size:15px!important;background:transparent!important;color:var(--ink)!important;min-height:24px!important}.searchHelp{font-size:12.5px;color:var(--muted);margin:8px 2px 0;line-height:1.35}.searchResults{margin-top:10px}.searchEmpty{padding:12px;border:1px dashed var(--line);border-radius:15px;color:var(--muted);font-size:13.5px;background:rgba(255,255,255,.56)}.searchResult{border:1px solid var(--line);border-radius:16px;background:#fff;padding:11px;margin-top:8px}.searchResultTitle{font-weight:900;color:var(--ink);font-size:15px;line-height:1.2}.searchMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.searchTag{background:var(--rose);color:var(--wine);border-radius:999px;padding:5px 8px;font-size:12px;font-weight:800}.searchActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.searchActionBtn{border:0;background:var(--rose);color:var(--wine);border-radius:999px;padding:7px 10px;font-size:12.5px;font-weight:900}.searchActionBtn.star{background:#fff3c4;color:#8a5b00;border:1px solid #f3d990}
.todayGroup{margin-top:10px}.todayGroup:first-child{margin-top:2px}.todayGroupTitle{display:flex;align-items:center;gap:6px;margin:8px 2px 7px;color:var(--wine);font-size:12.5px;font-weight:950}.todayGroupTitle span{background:var(--rose);border-radius:999px;padding:5px 9px}.todayMini{position:relative;display:flex!important;align-items:center!important;gap:9px!important}.todayMiniMain{flex:1;min-width:0}.todayMiniActions{display:flex;align-items:center;gap:6px;flex:none;flex-wrap:wrap;justify-content:flex-end}.todayMiniText{line-height:1.15}.todayDoneBtn{border:0;background:var(--rose);color:var(--wine);border-radius:999px;padding:7px 10px;font-size:12px;font-weight:900;white-space:nowrap;box-shadow:0 4px 10px rgba(138,18,56,.08)}.todayDoneBtn:active{transform:scale(.96)}.todayMini.routine .todayDoneBtn{display:none}.todayLateTag,.overdueTag{display:inline-flex;align-items:center;gap:4px;border-radius:999px;background:#ffe3e0;color:#a01838;font-weight:900;line-height:1;white-space:nowrap}.todayLateTag{padding:6px 9px;font-size:11.5px}.overdueTag{padding:7px 10px;font-size:13px;margin-left:4px}.overdueItem{border-color:#efc7c2!important;box-shadow:0 10px 24px rgba(160,24,56,.08)!important}
.filter{gap:7px!important;padding:2px 2px 6px!important;scroll-padding-left:2px}.chip{font-size:14px!important;padding:8px 13px!important;border-radius:999px!important;min-height:38px!important;box-shadow:0 4px 12px rgba(82,44,37,.04)}.chip.active{box-shadow:0 8px 16px rgba(138,18,56,.16)!important}.sectionHead{margin-top:20px!important}.sectionTitle{min-width:0}.sectionTitle h2{white-space:nowrap}.miniBtn{padding:8px 11px!important;font-size:12.5px!important}
.historyBox,.routineBox{margin:24px 0 10px;border-top:1px solid var(--line);padding-top:14px}.routineBox{margin-top:20px}.historyBox summary,.routineBox summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:10px;background:rgba(255,253,251,.94);border:1px solid var(--line);border-radius:18px;padding:14px 15px;box-shadow:var(--shadow2);color:var(--wine);font-weight:900;font-size:18px;cursor:pointer}.historyBox summary::-webkit-details-marker,.routineBox summary::-webkit-details-marker{display:none}.historyBox summary b,.routineBox summary b{display:block;font-size:18px;line-height:1.05}.historyBox summary small,.routineBox summary small{display:block;font-size:12px;color:var(--muted);font-weight:700;margin-top:3px}.historyBox[open] summary small,.routineBox[open] summary small{color:var(--wine)}.historyCount,.routineCountMini{background:var(--rose);color:var(--wine);border-radius:999px;padding:5px 10px;font-size:12px;font-weight:900;white-space:nowrap}.historyBox #doneList,.routineBox #routineList{margin-top:10px}.routineBox .empty,.historyBox .empty{margin-top:10px}
@media(max-width:390px){main{padding-top:30px!important;padding-left:20px!important;padding-right:16px!important}.hello h1{font-size:24px!important}.todayMini{gap:7px!important}.todayMiniTime{min-width:44px!important}.todayDoneBtn,.todayLateTag{font-size:11px!important;padding:6px 8px!important}#taskList .item{padding-right:54px!important}.todayGroupTitle{font-size:12px}.chip{font-size:13.5px!important;padding:7px 11px!important}.sectionTitle h2{font-size:21px!important}.miniBtn{font-size:12px!important;padding:7px 10px!important}.historyBox summary,.routineBox summary{padding:13px 14px}.historyBox summary b,.routineBox summary b{font-size:17px}.searchHeader b{font-size:17px}.grid{gap:7px!important}.stat{font-size:11.5px!important}}
@supports(padding:max(0px)){main{padding-top:max(28px,calc(env(safe-area-inset-top) + 10px))!important;padding-left:max(22px,calc(env(safe-area-inset-left) + 22px))!important;padding-right:max(18px,calc(env(safe-area-inset-right) + 18px))!important}}
`;

const PLANNER_PATCH_JS = `
<script>
(function(){
  const VERSION='12.6';
  function setVersion(){try{var el=document.getElementById('versionLine');if(el)el.textContent='Versão '+VERSION+' • Prioridade em botão.';document.title='Meu Planner — Bruna V'+VERSION;}catch(e){}}
  function allTasks(){try{return Array.isArray(tasks)?tasks:[]}catch(e){return[]}}
  function persist(){try{localStorage.setItem('brunaTasks',JSON.stringify(allTasks()))}catch(e){}}
  function safeEsc(v){try{return esc(String(v||''))}catch(e){return String(v||'').replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||'&#39;'})}}
  function safeNorm(v){return String(v||'').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase()}
  function dateLabel(v){if(!v)return'';try{var p=String(v).split('-');if(p.length===3)return p[2]+'/'+p[1]+'/'+p[0]}catch(e){}return v}
  function catName(c){try{return catLabel(c)}catch(e){return c||'Sem pasta'}}
  function isTaskSafe(t){try{return t&&!isRoutine(t)}catch(e){return t&&!t.recurrence}}
  function dateKeyForTimeOnly(time){var d=new Date(),p=String(time||'08:00').split(':').map(Number);d.setHours(p[0]||0,p[1]||0,0,0);if(d.getTime()<=Date.now()+5000)d.setDate(d.getDate()+1);try{return dateKey(d)}catch(e){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}}
  function installLogicFixes(){
    try{shouldSchedule=function(t){return !t.paused&&!t.done&&(hasReminderIntent(t.text)||!!t.recurrence||!!t.time||!!(t.date&&t.time))};window.shouldSchedule=shouldSchedule;}catch(e){}
    try{makeItem=function(text,old){var c=classify(text),time=parseTime(text),reminder=parseReminder(text),recurrence=parseRecurrence(text);if(recurrence&&!time)time='08:00';return {id:old&&old.id?old.id:Date.now(),text:text,cat:c.cat,sub:c.sub,date:recurrence?'':(parseDate(text)||(time?dateKeyForTimeOnly(time):'')),time:time,reminder:reminder,recurrence:recurrence,paused:old?!!old.paused:false,done:old?!!old.done:false,priority:old?!!old.priority:false,created:old&&old.created?old.created:new Date().toISOString(),edited:new Date().toISOString()}};window.makeItem=makeItem;}catch(e){}
  }
  window.togglePriority=function(id){try{var t=allTasks().find(function(x){return Number(x.id)===Number(id)});if(!t)return;t.priority=!t.priority;try{calendarChanged()}catch(e){}persist();try{render()}catch(e){}try{toast(t.priority?'⭐ Marcada como prioridade.':'☆ Prioridade removida.')}catch(e){}}catch(e){}};
  function buildCard(t,routine,history){
    var scheduled=scheduledInfo(t.id);
    var recurring=t.recurrence?' <span class="reminder">🔁 '+safeEsc(t.recurrence.label)+'</span>':'';
    var schedLabel=scheduled?' <span class="reminder">✅ '+(scheduled.recurring?'avisos agendados':'aviso agendado')+'</span>':'';
    var pauseLabel=t.paused?' <span class="reminder">⏸ pausada</span>':'';
    var left=routine?'<div class="itemLead">'+iconFor(t,true)+'</div>':'<button class="check" onclick="toggle('+t.id+')">'+(t.done?'✓':'')+'</button>';
    var priorityButton=(!routine&&!history&&!t.done)?'<button class="smallAction priorityAction '+(t.priority?'on':'')+'" onclick="togglePriority('+t.id+')">'+(t.priority?'⭐ Prioridade':'☆ Prioridade')+'</button>':'';
    var actions=routine?'<button class="smallAction" onclick="toggleRoutine('+t.id+')">'+(t.paused?'▶️ Ativar rotina':'⏸ Pausar rotina')+'</button><button class="smallAction" onclick="editItem('+t.id+')">✎ Editar</button>':(history?'<button class="smallAction" onclick="toggle('+t.id+')">↩️ Reabrir</button>':'')+priorityButton+'<button class="smallAction" onclick="editItem('+t.id+')">✎ Editar</button>';
    var isPr=!!(t.priority&&!routine&&!history&&!t.done);
    var priorityTag=isPr?' <span class="priorityTag">⭐ Prioridade</span>':'';
    var cls='item '+(routine?'routineItem ':'')+(history?'historyItem ':'')+(t.done?'done ':'')+(t.paused?'paused ':'')+(isPr?'priorityItem ':'');
    var meta='<span class="tag">'+safeEsc(catName(t.cat))+'</span>'+(t.sub?'<span class="tag">'+safeEsc(t.sub)+'</span>':'')+(t.date?' <span class="reminder">📅 '+new Date(t.date+'T12:00').toLocaleDateString('pt-BR')+'</span>':'')+(t.time?' <span class="time">🕐 '+safeEsc(t.time)+'</span>':'')+(t.reminder?' <span class="reminder">🔔 '+reminderLabel(t.reminder)+'</span>':'')+recurring+pauseLabel+schedLabel+priorityTag;
    return '<div class="'+cls+'">'+left+'<div class="itemBody"><div class="itemText">'+safeEsc(t.text)+'</div><div class="meta">'+meta+'</div><div class="itemActions">'+actions+'</div></div><button class="btn secondary deleteBtn" onclick="del('+t.id+')">×</button></div>';
  }
  function installCard(){try{card=buildCard;window.card=buildCard;}catch(e){}}
  function sortedTasks(arr){return arr.slice().sort(function(a,b){return (b.priority?1:0)-(a.priority?1:0)||((a.date||'9999')+(a.time||'99')).localeCompare((b.date||'9999')+(b.time||'99'))})}
  function installRender(){try{render=function(){var today=dateKey(new Date());var activeItems=tasks.filter(isActive);document.getElementById('todayCount').textContent=tasks.filter(function(t){return !isRoutine(t)&&!t.done&&t.date===today}).length;document.getElementById('schoolCount').textContent=activeItems.filter(function(t){return t.cat==='Escola'}).length;document.getElementById('taskCount').textContent=tasks.filter(function(t){return !isRoutine(t)&&!t.done}).length;document.getElementById('routineCount').textContent=tasks.filter(function(t){return isRoutine(t)&&isActive(t)}).length;document.getElementById('filters').innerHTML=folders.map(function(c){return '<button class="chip '+(c===active?'active':'')+'" onclick="active=\''+c+'\';render()">'+safeEsc(catName(c))+'</button>'}).join('');renderList('taskList',sortedTasks(filtered(tasks.filter(function(t){return !isRoutine(t)&&!t.done}))),false,false);renderList('routineList',filtered(tasks.filter(isRoutine)),true,false);renderList('doneList',filtered(tasks.filter(function(t){return !isRoutine(t)&&t.done})),false,true);try{renderTodayAgenda()}catch(e){}setTimeout(afterRender,0)};window.render=render;}catch(e){}}
  function routineCountMini(){try{return allTasks().filter(function(t){return isRoutine(t)&&isActive(t)}).length}catch(e){return 0}}
  function historyCountMini(){try{return allTasks().filter(function(t){return isTaskSafe(t)&&t.done}).length}catch(e){return 0}}
  function updateFoldCounts(){var r=document.getElementById('routineCountMini'),h=document.getElementById('historyCount');if(r)r.textContent=String(routineCountMini());if(h)h.textContent=String(historyCountMini())}
  function setupRoutineAccordion(){var list=document.getElementById('routineList');if(!list)return;if(list.closest&&list.closest('.routineBox')){updateFoldCounts();return}var head=list.previousElementSibling;while(head&&head.nodeType!==1)head=head.previousElementSibling;if(!head||!head.classList||!head.classList.contains('sectionHead'))return;var box=document.createElement('details');box.className='routineBox';box.id='routineBox';var sum=document.createElement('summary');sum.innerHTML='<span><b>🔁 Minhas rotinas</b><small>Toque para abrir</small></span><span class="routineCountMini" id="routineCountMini">0</span>';head.parentNode.insertBefore(box,head);head.remove();box.appendChild(sum);box.appendChild(list);updateFoldCounts()}
  function setupHistoryAccordion(){var list=document.getElementById('doneList');if(!list)return;if(list.closest&&list.closest('.historyBox')){updateFoldCounts();return}var head=list.previousElementSibling;while(head&&head.nodeType!==1)head=head.previousElementSibling;if(!head||!head.classList||!head.classList.contains('sectionHead'))return;var box=document.createElement('details');box.className='historyBox';box.id='historyBox';var sum=document.createElement('summary');sum.innerHTML='<span><b>🕘 Histórico</b><small>Toque para abrir</small></span><span class="historyCount" id="historyCount">0</span>';head.parentNode.insertBefore(box,head);head.remove();box.appendChild(sum);box.appendChild(list);updateFoldCounts()}
  function putTasksBeforeRoutines(){try{var tl=document.getElementById('taskList');if(!tl)return;var th=tl.previousElementSibling;while(th&&th.nodeType!==1)th=th.previousElementSibling;if(!th||!th.classList||!th.classList.contains('sectionHead'))return;var rb=document.getElementById('routineBox')||document.getElementById('routineList');if(!rb||!rb.parentNode)return;rb.parentNode.insertBefore(th,rb);rb.parentNode.insertBefore(tl,rb)}catch(e){}}
  function eventTime(t){try{return eventDueAt(t)}catch(e){if(t&&t.date&&t.time)return new Date(t.date+'T'+t.time);return null}}
  function isLate(t){if(!t||t.done||!isTaskSafe(t)||!isActive(t))return false;var ev=eventTime(t);return !!(ev&&ev.getTime()<Date.now())}
  function agendaItems(){var today=dateKey(new Date()),out=[];allTasks().forEach(function(t){if(!isActive(t))return;if(!isTaskSafe(t)){if(routineOccursToday(t)){var rt=t.time||'08:00';out.push({id:t.id,text:t.text,time:rt,cat:t.cat,routine:true,late:false,priority:false,stamp:todayAt(rt).getTime()})}return}var ev=eventTime(t),late=isLate(t);if(t.date===today||(ev&&dateKey(ev)===today)||late){var tm=t.time||(ev?String(ev.getHours()).padStart(2,'0')+':'+String(ev.getMinutes()).padStart(2,'0'):'Hoje');out.push({id:t.id,text:t.text,time:tm,cat:t.cat,routine:false,late:late,priority:!!t.priority,stamp:ev?ev.getTime():todayAt('23:59').getTime()})}});return out.sort(function(a,b){return (b.priority?1:0)-(a.priority?1:0)||a.stamp-b.stamp}).slice(0,8)}
  function todayItemHtml(x){var late=x.late?'<span class="todayLateTag">⚠️ Atrasada</span>':'';var pr=x.priority?'<span class="priorityTag">⭐ Prioridade</span>':'';var btn=x.routine?'':'<button class="todayDoneBtn" onclick="completeAgendaItem('+x.id+')">✓ Feito</button>';return '<div class="todayMini '+(x.routine?'routine':'task')+(x.late?' overdueItem':'')+(x.priority?' priorityItem':'')+'"><span class="todayMiniTime">'+safeEsc(x.time)+'</span><div class="todayMiniMain"><div class="todayMiniText">'+safeEsc(x.text)+'</div><div class="todayMiniCat">'+(x.routine?'Rotina • ':'')+safeEsc(catName(x.cat))+'</div></div><div class="todayMiniActions">'+pr+late+btn+'</div></div>'}
  function groupHtml(title,items){if(!items.length)return'';return '<div class="todayGroup"><div class="todayGroupTitle"><span>'+title+'</span></div>'+items.map(todayItemHtml).join('')+'</div>'}
  window.completeAgendaItem=function(id){try{toggle(id)}catch(e){}};
  function installTodayAgenda(){try{renderTodayAgenda=function(){var list=document.getElementById('todayAgendaList'),label=document.getElementById('todayDateLabel');if(!list)return;if(label&&typeof agendaDateLabel==='function')label.textContent=agendaDateLabel();var items=agendaItems();if(!items.length){list.innerHTML='<div class="todayEmpty">Nada marcado para hoje. Ótimo respiro 🌿</div>';return}var late=items.filter(function(x){return x.late&&!x.routine});var up=items.filter(function(x){return !x.late&&!x.routine});var routines=items.filter(function(x){return x.routine});list.innerHTML=groupHtml('⚠️ Atrasadas',late)+groupHtml('⏰ Próximas tarefas',up)+groupHtml('🔁 Rotinas de hoje',routines)};window.renderTodayAgenda=renderTodayAgenda}catch(e){}}
  function setupSearch(){try{var main=document.querySelector('main');if(!main)return;var panel=document.getElementById('realSearchPanel');if(!panel){panel=document.createElement('section');panel.id='realSearchPanel';panel.className='searchPanel';panel.innerHTML='<div class="searchHeader"><b>🔎 Buscar tarefas</b><button class="searchClose" id="realSearchClose">×</button></div><div class="searchInputWrap"><span>⌕</span><input id="realSearchInput" placeholder="Digite: prova, vinho, boleto, tour..." autocomplete="off"></div><div class="searchHelp">Procura em tarefas, rotinas, histórico e pastas.</div><div class="searchResults" id="realSearchResults"><div class="searchEmpty">Digite uma palavra para buscar.</div></div>';var today=document.querySelector('.todayPanel');main.insertBefore(panel,today||main.children[1])}var input=document.getElementById('realSearchInput'),results=document.getElementById('realSearchResults'),close=document.getElementById('realSearchClose');function renderSearch(){var q=safeNorm(input.value);if(!q){results.innerHTML='<div class="searchEmpty">Digite uma palavra para buscar.</div>';return}var found=allTasks().filter(function(t){var hay=safeNorm([t.text,catName(t.cat),t.sub,t.date,t.time,t.recurrence,t.done?'historico':'pendente',t.priority?'prioridade':''].join(' '));return hay.indexOf(q)>=0}).slice(0,20);if(!found.length){results.innerHTML='<div class="searchEmpty">Nada encontrado.</div>';return}results.innerHTML=found.map(function(t){var tags=['📁 '+catName(t.cat)];if(t.sub)tags.push(t.sub);if(t.date)tags.push('📅 '+dateLabel(t.date));if(t.time)tags.push('🕘 '+t.time);if(t.done)tags.push('Histórico');if(t.priority)tags.push('⭐ Prioridade');var act='<button class="searchActionBtn" onclick="editItem('+t.id+')">✎ Editar</button>';if(isTaskSafe(t))act+='<button class="searchActionBtn star" onclick="togglePriority('+t.id+')">'+(t.priority?'Remover ⭐':'Marcar ⭐')+'</button>';if(isTaskSafe(t)&&!t.done)act+='<button class="searchActionBtn" onclick="toggle('+t.id+')">✓ Feito</button>';if(isTaskSafe(t)&&t.done)act+='<button class="searchActionBtn" onclick="toggle('+t.id+')">↩ Reabrir</button>';return '<div class="searchResult"><div class="searchResultTitle">'+safeEsc(t.text)+'</div><div class="searchMeta">'+tags.map(function(x){return '<span class="searchTag">'+safeEsc(x)+'</span>'}).join('')+'</div><div class="searchActions">'+act+'</div></div>'}).join('')}input.oninput=renderSearch;close.onclick=function(){panel.classList.remove('open')};var b=document.getElementById('searchBtn');if(b)b.onclick=function(){panel.classList.add('open');setTimeout(function(){input.focus();renderSearch()},80)};window.openSearch=function(){panel.classList.add('open');setTimeout(function(){input.focus();renderSearch()},80)}}catch(e){}}
  function afterRender(){setVersion();setupRoutineAccordion();setupHistoryAccordion();putTasksBeforeRoutines();updateFoldCounts()}
  function start(){setVersion();installLogicFixes();installCard();installTodayAgenda();setupSearch();installRender();try{render()}catch(e){}setTimeout(afterRender,80);setTimeout(afterRender,400);setTimeout(function(){try{render()}catch(e){}},900);setInterval(afterRender,3000)}
  if(document.readyState==='loading')window.addEventListener('load',start);else start();
})();
<\/script>`;

function injectBeforeClose(source,closeTag,addition){
  if(!addition)return source;
  if(source.includes(addition.slice(0,80)))return source;
  return source.replace('\n'+closeTag,'\n'+addition+'\n'+closeTag);
}

function patchPlannerHtml(text){
  let s=text;
  s=s.replace(/Meu Planner — Bruna V\d+\.\d+/g,'Meu Planner — Bruna V12.6');
  s=s.replace(/Versão \d+\.\d+ • [^<]+/g,'Versão 12.6 • Prioridade em botão.');
  s=s.replace(/version:'\d+\.\d+'/g,"version:'12.6'");
  s=s.replace(/function shouldSchedule\(t\)\{[^}]+\}/,"function shouldSchedule(t){return !t.paused&&!t.done&&(hasReminderIntent(t.text)||!!t.recurrence||!!t.time||!!(t.date&&t.time))}");
  if(!s.includes('function dateKeyForTimeOnly(time)')){
    s=s.replace('function makeItem(text,old){',"function dateKeyForTimeOnly(time){let d=new Date(),p=(time||'08:00').split(':').map(Number);d.setHours(p[0]||0,p[1]||0,0,0);if(d.getTime()<=Date.now()+5000)d.setDate(d.getDate()+1);return dateKey(d)}\nfunction makeItem(text,old){");
  }
  s=s.replace("date:recurrence?'':parseDate(text),time,","date:recurrence?'':(parseDate(text)||(time?dateKeyForTimeOnly(time):'')),time,");
  s=s.replace(/sendAt\.getTime\(\)<Date\.now\(\)\+20000/g,'sendAt.getTime()<Date.now()+5000');
  s=s.replace(/sendAt\.getTime\(\)<Date\.now\(\)\+15000/g,'sendAt.getTime()<Date.now()+5000');
  if(!s.includes('Ajuste 12.6: prioridade em botão'))s=injectBeforeClose(s,'</style>',PLANNER_PATCH_CSS);
  if(!s.includes("const VERSION='12.6'"))s=injectBeforeClose(s,'</body>',PLANNER_PATCH_JS);
  return s;
}

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.mode!=='navigate'&&request.destination!=='document')return;
  event.respondWith(fetch(request,{cache:'no-store'}).then(async response=>{
    const type=response.headers.get('content-type')||'';
    if(!type.includes('text/html'))return response;
    const html=await response.text();
    const patched=patchPlannerHtml(html);
    return new Response(patched,{status:response.status,statusText:response.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
  }).catch(()=>fetch(request)));
});
