importScripts("https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js");

// Versão 11.5 — busca real por tarefas.
// Mantém agenda agrupada, atrasadas, botão Feito, topo com respiro e seções recolhíveis.
self.addEventListener('install', event => self.skipWaiting());
self.addEventListener('activate', event => event.waitUntil(self.clients.claim()));

const PLANNER_PATCH_CSS = `
/* Ajuste 11.5: busca real + agenda agrupada */
html,body{width:100%;max-width:100%;overflow-x:hidden!important;position:relative;touch-action:pan-y}
body{overscroll-behavior-x:none}
main{width:100%;max-width:780px;margin:0 auto;padding-top:28px!important;padding-bottom:24px!important;padding-left:calc(22px + env(safe-area-inset-left))!important;padding-right:calc(18px + env(safe-area-inset-right))!important;overflow:hidden}
.topbar{max-width:100%;align-items:flex-start!important;margin:8px 0 12px!important;min-height:52px!important}
.hello h1{font-size:25px!important;line-height:1.04!important;letter-spacing:-.55px!important;margin:0!important;white-space:nowrap!important}.hello p{font-size:13px!important;line-height:1.25!important;margin-top:5px!important}
.topActions{padding-top:2px!important;flex:none!important}.roundBtn{width:38px!important;height:38px!important}.hero{margin-top:4px!important}.heroTitle{line-height:1.2!important}
.topbar,.hero,.todayPanel,.grid,.sectionHead,.filter,.item,.toolsBox,.historyBox,.routineBox,.searchPanel{max-width:100%}
.searchPanel{display:none;background:rgba(255,253,251,.96);border:1px solid var(--line);border-radius:22px;padding:14px;margin:12px 0 14px;box-shadow:var(--shadow2)}.searchPanel.open{display:block}.searchHeader{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.searchHeader b{font-size:18px;color:var(--wine)}.searchClose{border:0;background:var(--rose);color:var(--wine);border-radius:999px;width:34px;height:34px;font-size:18px;font-weight:900}.searchInputWrap{display:flex;align-items:center;gap:8px;background:white;border:1px solid var(--line);border-radius:16px;padding:10px 12px}.searchInputWrap span{color:var(--muted)}#realSearchInput{border:0;outline:0;width:100%;font-size:15px;background:transparent;color:var(--ink)}.searchHelp{font-size:12.5px;color:var(--muted);margin:8px 2px 0;line-height:1.35}.searchResults{margin-top:10px}.searchEmpty{padding:12px;border:1px dashed var(--line);border-radius:15px;color:var(--muted);font-size:13.5px;background:rgba(255,255,255,.56)}.searchResult{border:1px solid var(--line);border-radius:16px;background:#fff;padding:11px;margin-top:8px}.searchResultTitle{font-weight:900;color:var(--ink);font-size:15px;line-height:1.2}.searchMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.searchTag{background:var(--rose);color:var(--wine);border-radius:999px;padding:5px 8px;font-size:12px;font-weight:800}.searchActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.searchActionBtn{border:0;background:var(--rose);color:var(--wine);border-radius:999px;padding:7px 10px;font-size:12.5px;font-weight:900}
.todayGroup{margin-top:10px}.todayGroup:first-child{margin-top:2px}.todayGroupTitle{display:flex;align-items:center;gap:6px;margin:8px 2px 7px;color:var(--wine);font-size:12.5px;font-weight:950;letter-spacing:.01em;text-transform:none}.todayGroupTitle span{background:var(--rose);border-radius:999px;padding:5px 9px}
.todayMini{position:relative;display:flex!important;align-items:center!important;gap:9px!important}.todayMiniMain{flex:1;min-width:0}.todayMiniActions{display:flex;align-items:center;gap:6px;flex:none;flex-wrap:wrap;justify-content:flex-end}.todayMiniText{line-height:1.15}.todayDoneBtn{border:0;background:var(--rose);color:var(--wine);border-radius:999px;padding:7px 10px;font-size:12px;font-weight:900;white-space:nowrap;box-shadow:0 4px 10px rgba(138,18,56,.08)}.todayDoneBtn:active{transform:scale(.96)}.todayMini.routine .todayDoneBtn{display:none}
.todayLateTag,.overdueTag{display:inline-flex;align-items:center;gap:4px;border-radius:999px;background:#ffe3e0;color:#a01838;font-weight:900;line-height:1;white-space:nowrap}.todayLateTag{padding:6px 9px;font-size:11.5px}.overdueTag{padding:7px 10px;font-size:13px;margin-left:4px}.overdueItem{border-color:#efc7c2!important;box-shadow:0 10px 24px rgba(160,24,56,.08)!important}
.filter{gap:7px!important;padding:2px 2px 6px!important;scroll-padding-left:2px}.chip{font-size:14px!important;padding:8px 13px!important;border-radius:999px!important;min-height:38px!important;box-shadow:0 4px 12px rgba(82,44,37,.04)}.chip.active{box-shadow:0 8px 16px rgba(138,18,56,.16)!important}
.sectionHead{margin-top:20px!important}.sectionTitle{min-width:0}.sectionTitle h2{white-space:nowrap}.miniBtn{padding:8px 11px!important;font-size:12.5px!important}
.historyBox,.routineBox{margin:24px 0 10px;border-top:1px solid var(--line);padding-top:14px}.routineBox{margin-top:20px}.historyBox summary,.routineBox summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:10px;background:rgba(255,253,251,.94);border:1px solid var(--line);border-radius:18px;padding:14px 15px;box-shadow:var(--shadow2);color:var(--wine);font-weight:900;font-size:18px;cursor:pointer}.historyBox summary::-webkit-details-marker,.routineBox summary::-webkit-details-marker{display:none}.historyBox summary b,.routineBox summary b{display:block;font-size:18px;line-height:1.05}.historyBox summary small,.routineBox summary small{display:block;font-size:12px;color:var(--muted);font-weight:700;margin-top:3px}.historyBox[open] summary small,.routineBox[open] summary small{color:var(--wine)}.historyCount,.routineCountMini{background:var(--rose);color:var(--wine);border-radius:999px;padding:5px 10px;font-size:12px;font-weight:900;white-space:nowrap}.historyBox #doneList,.routineBox #routineList{margin-top:10px}.routineBox .empty,.historyBox .empty{margin-top:10px}
@media(max-width:390px){main{padding-top:30px!important;padding-left:20px!important;padding-right:16px!important}.hello h1{font-size:24px!important}.todayMini{gap:7px!important}.todayMiniTime{min-width:44px!important}.todayDoneBtn,.todayLateTag{font-size:11px!important;padding:6px 8px!important}.todayGroupTitle{font-size:12px}.chip{font-size:13.5px!important;padding:7px 11px!important}.sectionTitle h2{font-size:21px!important}.miniBtn{font-size:12px!important;padding:7px 10px!important}.historyBox summary,.routineBox summary{padding:13px 14px}.historyBox summary b,.routineBox summary b{font-size:17px}.searchHeader b{font-size:17px}}
@supports(padding:max(0px)){main{padding-top:max(28px,calc(env(safe-area-inset-top) + 10px))!important;padding-left:max(22px,calc(env(safe-area-inset-left) + 22px))!important;padding-right:max(18px,calc(env(safe-area-inset-right) + 18px))!important}}
`;

const PLANNER_PATCH_JS = `
<script>
(function(){
  function fixX(){ if(window.scrollX) window.scrollTo(0, window.scrollY); }
  function allTasks(){ try{return (typeof tasks!=='undefined'&&Array.isArray(tasks))?tasks:[]}catch(e){return[]} }
  function safeEsc(v){ try{return esc(String(v||''));}catch(e){return String(v||'').replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})} }
  function norm(v){ return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(); }
  function catName(c){ try{return catLabel(c)}catch(e){return c||'Sem pasta'} }
  function enhanceFilter(){ var f=document.getElementById('filters'); if(f&&!f.dataset.compactHint){f.dataset.compactHint='1';f.setAttribute('aria-label','Pastas — arraste para o lado para ver todas');} }
  function dkTime(time){ var d=new Date(),p=String(time||'08:00').split(':').map(Number); d.setHours(p[0]||0,p[1]||0,0,0); if(d.getTime()<=Date.now()+5000)d.setDate(d.getDate()+1); return (typeof dateKey==='function')?dateKey(d):d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }
  function fixExistingTimeOnlyTasks(){ try{ var changed=false; allTasks().forEach(function(t){ if(t&&t.time&&!t.date&&!t.recurrence&&!t.done){t.date=dkTime(t.time);changed=true;} }); if(changed){localStorage.setItem('brunaTasks',JSON.stringify(allTasks())); if(typeof render==='function')render(); if(typeof schedulePendingReminders==='function')schedulePendingReminders(false);} }catch(e){} }
  function routineCount(){try{return allTasks().filter(function(t){return isRoutine(t)&&isActive(t)}).length}catch(e){return document.querySelectorAll('#routineList .routineItem').length}}
  function historyDoneCount(){try{return allTasks().filter(function(t){return !isRoutine(t)&&t.done}).length}catch(e){return document.querySelectorAll('#doneList .historyItem').length}}
  function updateFoldCounts(){var r=document.getElementById('routineCountMini'),h=document.getElementById('historyCount'); if(r)r.textContent=String(routineCount()); if(h)h.textContent=String(historyDoneCount());}
  function setupRoutineAccordion(){var list=document.getElementById('routineList'); if(!list)return; if(list.closest&&list.closest('.routineBox')){updateFoldCounts();return;} var head=list.previousElementSibling; while(head&&head.nodeType!==1)head=head.previousElementSibling; if(!head||!head.classList||!head.classList.contains('sectionHead'))return; var box=document.createElement('details'); box.className='routineBox'; box.id='routineBox'; var sum=document.createElement('summary'); sum.innerHTML='<span><b>🔁 Minhas rotinas</b><small>Toque para abrir</small></span><span class="routineCountMini" id="routineCountMini">0</span>'; head.parentNode.insertBefore(box,head); head.remove(); box.appendChild(sum); box.appendChild(list); updateFoldCounts();}
  function setupSectionOrder(){var rb=document.getElementById('routineBox'),tl=document.getElementById('taskList'); if(!rb||!tl||!rb.parentNode)return; var th=tl.previousElementSibling; while(th&&th.nodeType!==1)th=th.previousElementSibling; if(!th||!th.classList||!th.classList.contains('sectionHead'))return; rb.parentNode.insertBefore(th,rb); rb.parentNode.insertBefore(tl,rb);}
  function setupHistoryAccordion(){var list=document.getElementById('doneList'); if(!list)return; if(list.closest&&list.closest('.historyBox')){updateFoldCounts();return;} var head=list.previousElementSibling; while(head&&head.nodeType!==1)head=head.previousElementSibling; if(!head||!head.classList||!head.classList.contains('sectionHead'))return; var box=document.createElement('details'); box.className='historyBox'; box.id='historyBox'; var sum=document.createElement('summary'); sum.innerHTML='<span><b>🕘 Histórico</b><small>Toque para abrir</small></span><span class="historyCount" id="historyCount">0</span>'; head.parentNode.insertBefore(box,head); head.remove(); box.appendChild(sum); box.appendChild(list); updateFoldCounts();}
  function setupAccordions(){setupRoutineAccordion();setupSectionOrder();setupHistoryAccordion();updateFoldCounts();}
  function eventTime(t){try{return eventDueAt(t)}catch(e){ if(t&&t.date&&t.time)return new Date(t.date+'T'+t.time); return null; }}
  function isLate(t){ if(!t||t.done||isRoutine(t)||!isActive(t))return false; var ev=eventTime(t); return !!(ev&&ev.getTime()<Date.now()); }
  function agendaItems(){var today=dateKey(new Date()),out=[]; allTasks().forEach(function(t){ if(!isActive(t))return; if(isRoutine(t)){ if(routineOccursToday(t)){var rt=t.time||'08:00'; out.push({id:t.id,text:t.text,time:rt,cat:t.cat,routine:true,late:false,stamp:todayAt(rt).getTime()});} return; } var ev=eventTime(t); var late=isLate(t); if(t.date===today||(ev&&dateKey(ev)===today)||late){var tm=t.time||(ev?pad(ev.getHours())+':'+pad(ev.getMinutes()):'Hoje'); out.push({id:t.id,text:t.text,time:tm,cat:t.cat,routine:false,late:late,stamp:ev?ev.getTime():todayAt('23:59').getTime()});} }); return out.sort(function(a,b){return a.stamp-b.stamp}).slice(0,8);}
  function itemHtml(x){var late=x.late?'<span class="todayLateTag">⚠️ Atrasada</span>':''; var btn=x.routine?'':'<button class="todayDoneBtn" onclick="completeAgendaItem('+x.id+')">✓ Feito</button>'; return '<div class="todayMini '+(x.routine?'routine':'task')+(x.late?' overdueItem':'')+'"><span class="todayMiniTime">'+safeEsc(x.time)+'</span><div class="todayMiniMain"><div class="todayMiniText">'+safeEsc(x.text)+'</div><div class="todayMiniCat">'+(x.routine?'Rotina • ':'')+safeEsc(catName(x.cat))+'</div></div><div class="todayMiniActions">'+late+btn+'</div></div>';}
  function groupHtml(title,items){ if(!items.length)return ''; return '<div class="todayGroup"><div class="todayGroupTitle"><span>'+title+'</span></div>'+items.map(itemHtml).join('')+'</div>'; }
  window.completeAgendaItem=function(id){try{if(typeof toggle==='function')toggle(id);}catch(e){}};
  function applyTodayAgenda(){ try{ if(typeof renderTodayAgenda!=='function')return; if(window.__todayGroupedPatchApplied)return; window.__todayGroupedPatchApplied=true; renderTodayAgenda=function(){var list=document.getElementById('todayAgendaList'),label=document.getElementById('todayDateLabel'); if(!list)return; if(label)label.textContent=agendaDateLabel(); var items=agendaItems(); if(!items.length){list.innerHTML='<div class="todayEmpty">Nada marcado para hoje. Ótimo respiro 🌿</div>'; return;} var late=items.filter(function(x){return x.late&&!x.routine}); var upcoming=items.filter(function(x){return !x.late&&!x.routine}); var routines=items.filter(function(x){return x.routine}); list.innerHTML=groupHtml('⚠️ Atrasadas',late)+groupHtml('⏰ Próximas tarefas',upcoming)+groupHtml('🔁 Rotinas de hoje',routines);}; if(typeof render==='function')render(); }catch(e){} }
  function decorateOverdueCards(){try{ document.querySelectorAll('.item').forEach(function(card){var edit=card.querySelector('[onclick^="editItem("]'); if(!edit)return; var m=String(edit.getAttribute('onclick')||'').match(/editItem\((\d+)\)/); if(!m)return; var id=Number(m[1]),t=allTasks().find(function(x){return Number(x.id)===id}); var old=card.querySelector('.overdueTag'); if(old)old.remove(); card.classList.remove('overdueItem'); if(isLate(t)){card.classList.add('overdueItem'); var meta=card.querySelector('.meta'); if(meta){var tag=document.createElement('span'); tag.className='overdueTag'; tag.textContent='⚠️ Atrasada'; meta.appendChild(tag);}} }); }catch(e){} }
  function setupSearchPanel(){ if(document.getElementById('realSearchPanel')){hookSearchButton();return;} var main=document.querySelector('main'),hero=document.querySelector('.hero'); if(!main||!hero)return; var panel=document.createElement('section'); panel.className='searchPanel'; panel.id='realSearchPanel'; panel.innerHTML='<div class="searchHeader"><b>🔎 Buscar tarefas</b><button class="searchClose" id="searchCloseBtn" type="button">×</button></div><div class="searchInputWrap"><span>⌕</span><input id="realSearchInput" type="search" placeholder="Digite: prova, vinho, boleto, tour..." autocomplete="off"></div><div class="searchHelp">Procura em tarefas, rotinas, histórico e pastas.</div><div class="searchResults" id="searchResults"><div class="searchEmpty">Digite uma palavra para buscar.</div></div>'; hero.parentNode.insertBefore(panel,hero.nextSibling); document.getElementById('searchCloseBtn').addEventListener('click',function(){panel.classList.remove('open')}); document.getElementById('realSearchInput').addEventListener('input',function(){renderSearchResults(this.value)}); hookSearchButton(); }
  function openSearch(){setupSearchPanel();var p=document.getElementById('realSearchPanel'),i=document.getElementById('realSearchInput'); if(p){p.classList.add('open'); setTimeout(function(){try{i.focus()}catch(e){}},80); p.scrollIntoView({behavior:'smooth',block:'center'});} }
  function hookSearchButton(){var b=document.querySelector('.topActions .roundBtn, .topActions button'); if(!b||b.dataset.realSearchHook)return; b.dataset.realSearchHook='1'; b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();openSearch();},true); }
  function renderSearchResults(q){var out=document.getElementById('searchResults'); if(!out)return; var query=norm(q); if(!query){out.innerHTML='<div class="searchEmpty">Digite uma palavra para buscar.</div>';return;} var results=allTasks().filter(function(t){var hay=[t.text,t.cat,t.sub,catName(t.cat),t.date,t.time].join(' ');return norm(hay).indexOf(query)>-1;}).sort(function(a,b){return (a.done?1:0)-(b.done?1:0)||((a.date||'9999')+(a.time||'99')).localeCompare((b.date||'9999')+(b.time||'99'));}).slice(0,12); if(!results.length){out.innerHTML='<div class="searchEmpty">Não encontrei nada com “'+safeEsc(q)+'”.</div>';return;} out.innerHTML=results.map(searchResultHtml).join(''); }
  function searchResultHtml(t){var tags=[]; try{ if(isRoutine(t))tags.push('Rotina'); }catch(e){} if(t.done)tags.push('Concluída'); if(isLate(t))tags.push('Atrasada'); tags.push(catName(t.cat)); if(t.date)tags.push(t.date); if(t.time)tags.push(t.time); var action='<button class="searchActionBtn" onclick="editItem('+t.id+')">✎ Editar</button>'; if(!isRoutine(t)){action+='<button class="searchActionBtn" onclick="toggle('+t.id+')">'+(t.done?'↩ Reabrir':'✓ Feito')+'</button>';} return '<div class="searchResult"><div class="searchResultTitle">'+safeEsc(t.text)+'</div><div class="searchMeta">'+tags.map(function(x){return '<span class="searchTag">'+safeEsc(x)+'</span>';}).join('')+'</div><div class="searchActions">'+action+'</div></div>'; }
  function wrapRender(){ if(window.__foldPatchWrapped){setupAccordions();decorateOverdueCards();setupSearchPanel();return;} window.__foldPatchWrapped=true; var old=null; try{old=window.render||(typeof render==='function'?render:null);}catch(e){} if(typeof old==='function'){window.render=function(){var r=old.apply(this,arguments);setupAccordions();setTimeout(decorateOverdueCards,0);setTimeout(setupSearchPanel,0);return r;}; try{render=window.render;}catch(e){}} setupAccordions();decorateOverdueCards();setupSearchPanel();}
  window.addEventListener('load',function(){setTimeout(fixExistingTimeOnlyTasks,120);setTimeout(applyTodayAgenda,160);setTimeout(wrapRender,200);setTimeout(applyTodayAgenda,700);setTimeout(wrapRender,750);setInterval(function(){try{renderTodayAgenda();decorateOverdueCards();}catch(e){}},30000);setTimeout(fixX,80);setTimeout(fixX,400);setTimeout(enhanceFilter,500);});
  window.addEventListener('resize',fixX); document.addEventListener('touchend',fixX,{passive:true});
})();
<\/script>`;

function patchPlannerHtml(text){
  let s=text;
  s=s.replace(/Meu Planner — Bruna V\d+\.\d+/g,'Meu Planner — Bruna V11.5');
  s=s.replace(/Versão \d+\.\d+ • [^<]+/g,'Versão 11.5 • Busca real.');
  s=s.replace(/version:'\d+\.\d+'/g,"version:'11.5'");
  s=s.replace("function shouldSchedule(t){return !t.paused&&!t.done&&(hasReminderIntent(t.text)||!!t.recurrence||!!(t.date&&t.time))}","function shouldSchedule(t){return !t.paused&&!t.done&&(hasReminderIntent(t.text)||!!t.recurrence||!!t.time||!!(t.date&&t.time))}");
  if(!s.includes('function dateKeyForTimeOnly(time)')){s=s.replace('function makeItem(text,old){',"function dateKeyForTimeOnly(time){let d=new Date(),p=(time||'08:00').split(':').map(Number);d.setHours(p[0]||0,p[1]||0,0,0);if(d.getTime()<=Date.now()+5000)d.setDate(d.getDate()+1);return dateKey(d)}\nfunction makeItem(text,old){");}
  s=s.replace("date:recurrence?'':parseDate(text),time,","date:recurrence?'':(parseDate(text)||(time?dateKeyForTimeOnly(time):'')),time,");
  s=s.replace(/sendAt\.getTime\(\)<Date\.now\(\)\+20000/g,'sendAt.getTime()<Date.now()+5000');
  s=s.replace(/sendAt\.getTime\(\)<Date\.now\(\)\+15000/g,'sendAt.getTime()<Date.now()+5000');
  if(!s.includes('Ajuste 11.5: busca real + agenda agrupada')){s=s.replace('\n</style>','\n'+PLANNER_PATCH_CSS+'\n</style>');}
  if(!s.includes('function setupSearchPanel()')){s=s.replace('\n</body>',PLANNER_PATCH_JS+'\n</body>');}
  return s;
}

self.addEventListener('fetch',event=>{
  const request=event.request;
  if(request.mode!=='navigate'&&request.destination!=='document')return;
  event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{
    const type=response.headers.get('content-type')||'';
    if(!type.includes('text/html'))return response;
    return response.text().then(html=>new Response(patchPlannerHtml(html),{status:response.status,statusText:response.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}}));
  }).catch(()=>fetch(request)));
});
